Fix MBEDTLS_STATIC_ASSERT(ARRAY_LENGTH(foo), "...") in C99
When a `static_assert` or `_Static_assert` built-in is not available,
we implement `MBEDTLS_STATIC_ASSERT` with a hack that places the assertion
in a function parameter list. The assertion must not declare an anonymous
struct, otherwise GCC complains

> error: anonymous struct declared inside parameter list will not be visible outside of this definition or declaration

So instead of using a bit-field width as a compile-time integer that must be
positive, use an array length. This keeps GCC happy, but means that some
rare compilers won't complain because they think it's just some
variable-length array.

(`MBEDTLS_STATIC_ASSERT` itself uses an array length, not a bit-field width,
for the same reason.)

Signed-off-by: Gilles Peskine <Gilles.Peskine@arm.com>